---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-controller
rules:
  - apiGroups: ["*"]
    resources: ["configmaps", "namespaces"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-controller-binding
subjects:
  - kind: ServiceAccount
    namespace: nsm-system
    name: sriov-controller
roleRef:
  kind: ClusterRole
  name: sriov-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
spec:
  selector:
    matchLabels:
      app: sriov-controller
  template:
    metadata:
      labels:
        app: sriov-controller
    spec:
      serviceAccount: sriov-controller
      containers:
        - name: sriov-controller
          image: docker.io/networkservicemesh/sriov-controller:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: kubelet-socket
              mountPath: /var/lib/kubelet/device-plugins
            - name: sriov-controller-config
              mountPath: /var/lib/networkservicemesh/sriov-controller/config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
            type: DirectoryOrCreate
          name: kubelet-socket
        - hostPath:
            path: /var/lib/networkservicemesh/sriov-controller/config
            type: DirectoryOrCreate
          name: sriov-controller-config
metadata:
  name: sriov-controller
  namespace: nsm-system
