---
version: 2.1

commands:
  skip_on_pattern:
    description: "Skips running job if the only files in the change match the pattern"
    parameters:
      branch:
        type: string
        default: origin/master
    steps:
      - run:
          name: "Skips running job if the only files in the change match the pattern"
          command: |
            ./.circleci/skip_job_on_pattern.sh << parameters.branch >>

jobs:

# sanity
  test-sanity-check:
    resource_class: xlarge
    working_directory: /go/src/github.com/networkservicemesh/networkservicemesh
    docker:
      - image: circleci/golang:1.13-stretch
    steps:
      - checkout
      - run:
          name: Install Shellcheck
          command: ./.circleci/install-shellcheck.sh
      - run:
          name: Run Shellcheck
          command: make check
      - skip_on_pattern
      - run:
          command: |
            sudo apt-get install python-pip python3-pkg-resources
            pip install --user yamllint
      - run: yamllint -c .yamllint.yml --strict .
      - run: go version
      - run:
          name: Download Go Dependencies
          command: |
            ./scripts/for-each-module.sh "$(pwd)/scripts/go-mod-download.sh"
      - run:
          name: Check code formatting
          command: |
            make install-formatter
            make format
            git diff --exit-code || (echo 'Seems like your Go files are not properly formatted. Run `make format` in your branch and commit the changes.' && exit 1)
      - run: ./scripts/prepare-generate.sh
      - run: sudo ./scripts/install-protoc.sh
      - run: ./scripts/for-each-module.sh "go generate ./..."
      - run: git diff --exit-code || (echo 'Seems like your generated files are not actual. Run `go generate ./...` for each module in your branch and commit the changes.' && exit 1)
      - run: make vet
      - run: ./scripts/for-each-module.sh "go build ./..."
      - run: ./scripts/check_dependencies.sh
      - run:
          name: Integration tests
          command: |
            pushd test
            go test ./integration --list .* -tags basic recover usecase
            popd
      - run: mkdir -p ~/junit/
      - run:
          command: |
            export COMMIT="ci_${CIRCLE_WORKFLOW_ID}_${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            export CONTAINER_REPO="networkservicemeshci"
            export CONTAINER_FORCE_PULL="true"
            export INSECURE="true"
            ./scripts/run_unit_tests.sh
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
    environment:
      GO111MODULE: "on"

# code analysis
  test-static-code-analysis:
    resource_class: large
    docker:
      - image: circleci/golang:1.13-stretch
    steps:
      - checkout
      - skip_on_pattern
      - run:
          name: lint
          command: |
            ./scripts/lint-download.sh
            ./scripts/for-each-module.sh "$(pwd)/scripts/lint-check-diff.sh"
    environment:
      GO111MODULE: "on"
      LOG_LEVEL: "error"

# integration
  integration-tests:
    docker:
      - image: circleci/golang:1.13-stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - skip_on_pattern
      - run:
          command: |
            sudo ./.circleci/install-yq.sh
      - run:
          command: |
            sudo ./.circleci/set-nameserver.sh sudo
            sudo apt-get install gettext-base
      - run:
          name: "Install kubectl"
          command: |
            sudo ./scripts/install-kubectl.sh
      - run:
          name: "Install GKE deps"
          command: |
            sudo ./scripts/gke/install-gcloud-sdk.sh
      - run:
          name: "Install Azure deps"
          command: |
            sudo ./scripts/azure/install-azure-cli.sh
      - run:
          name: "Init AWS"
          command: |
            ./scripts/aws/aws-init.sh
            sudo cp "$HOME/bin/aws-iam-authenticator" /usr/local/bin/aws-iam-authenticator
      - run:
          name: "Install Helm"
          command: |
            ./scripts/install-helm.sh
            sudo cp "$HOME/bin/helm" /usr/local/bin/helm
      - run:
          name: Downloading go deps
          command: |
            export COMMIT="ci_${CIRCLE_WORKFLOW_ID}_${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            ./scripts/go-mod-download.sh
          no_output_timeout: 40m
      - run:
          name: Running integration tests
          command: |
            export COMMIT="ci_${CIRCLE_WORKFLOW_ID}_${CIRCLE_SHA1:8:8}"
            export CONTAINER_TAG="${COMMIT}"
            export REPO="networkservicemeshci"
            export CONTAINER_REPO=${REPO}
            echo "CONTAINER_REPO=${CONTAINER_REPO} COMMIT=${COMMIT}"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export STORE_LOGS_IN_ANY_CASES=true
            fi
            pushd test
            CGO_ENABLED=0 GOOS=linux go build -o ../cloudtest ./cloudtest/cmd/cloudtest
            popd
            ./cloudtest
          no_output_timeout: 40m
      - store_test_results:
          path: .tests/cloud_test/results/
      - store_artifacts:
          path: .tests/cloud_test/
      - store_artifacts:
          path: ~/postmortem
    environment:
      GO111MODULE: "on"
      NSM_NAMESPACE: "nsm-system"

# build
  build-container:
    parameters:
      container:
        type: string
    docker:
      - image: circleci/golang:1.13-stretch
    steps:
      - checkout
      - skip_on_pattern
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="ci_${CIRCLE_WORKFLOW_ID}_${CIRCLE_SHA1:8:8}"
            export TAG="${COMMIT}"
            export CONTAINER_REPO="networkservicemeshci"
            export GOPROXY=https://proxy.golang.org,direct
            make docker-<< parameters.container >>-build
            make docker-<< parameters.container >>-push

# build ready - empty job
  build-container-success:
    docker:
      - image: circleci/golang:1.13-stretch
    steps:
      - run:
          command: |
            echo "SUCCESS"

# docker push
  docker-push-tag:
    docker:
      - image: circleci/golang:1.13-stretch
    parameters:
      tag:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            export COMMIT="ci_${CIRCLE_WORKFLOW_ID}_${CIRCLE_SHA1:8:8}"
            export PULL_TAG="${COMMIT}"
            export TAG="<< parameters.tag >>"
            export REPO="networkservicemesh"
            export PULL_REPO="networkservicemeshci"
            export CONTAINERS=(nsmd nsmd-k8s nsmdp)
            export CONTAINERS=(${CONTAINERS[@]} proxy-nsmd proxy-nsmd-k8s)
            export CONTAINERS=(${CONTAINERS[@]} crossconnect-monitor nsm-init nsm-monitor admission-webhook)
            export CONTAINERS=(${CONTAINERS[@]} vppagent-dataplane)
            export CONTAINERS=(${CONTAINERS[@]} test-common vpp-test-common nsm-coredns)
            export CONTAINERS=(${CONTAINERS[@]} kernel-forwarder)
            export CONTAINERS=(${CONTAINERS[@]} spire-registration)
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            for c in ${CONTAINERS[@]}; do
              docker pull ${PULL_REPO}/${c}:${PULL_TAG}
              docker tag ${PULL_REPO}/${c}:${PULL_TAG} ${REPO}/${c}:${TAG}
              docker push ${REPO}/${c}:${TAG}
            done

# helm
  test-helm-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v2.3.0
    steps:
      - checkout
      - run:
          name: Check for only Doc Changes
          command: circleci-agent step halt
      - run:
          name: Install and lint Helm charts
          command: |
            .circleci/helm/test-charts.sh

# workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - test-sanity-check
      - test-static-code-analysis:
          name: "test-static-code-analysis"
          requires:
            - test-sanity-check
# build
      - build-container:
          name: "build-nsm-coredns"
          container: "nsm-coredns"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-nsmd"
          container: "nsmd"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-nsmd-k8s"
          container: "nsmd-k8s"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-nsmdp"
          container: "nsmdp"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-proxy-nsmd"
          container: "proxy-nsmd"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-proxy-nsmd-k8s"
          container: "proxy-nsmd-k8s"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-admission-webhook"
          container: "admission-webhook"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-crossconnect-monitor"
          container: "crossconnect-monitor"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-test-common"
          container: "test-common"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-vpp-test-common"
          container: "vpp-test-common"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-nsm-init"
          container: "nsm-init"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-nsm-monitor"
          container: "nsm-monitor"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-vppagent-dataplane"
          container: "vppagent-dataplane"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-kernel-forwarding-plane"
          container: "kernel-forwarder"
          requires:
            - test-sanity-check
      - build-container:
          name: "build-spire-registration"
          container: "spire-registration"
          requires:
            - test-sanity-check
      - build-container-success:
          requires:
            - build-nsmd
            - build-nsmd-k8s
            - build-nsmdp
            - build-proxy-nsmd
            - build-proxy-nsmd-k8s
            - build-admission-webhook
            - build-crossconnect-monitor
            - build-test-common
            - build-vpp-test-common
            - build-nsm-init
            - build-nsm-monitor
            - build-vppagent-dataplane
            - build-kernel-forwarding-plane
            - build-nsm-coredns
            - build-spire-registration

# Integration testing
      - integration-tests:
          name: "test-integration"
          requires:
            - build-container-success
# helm
      - test-helm-charts:
          name: "test-helm-charts"
          requires:
            - test-sanity-check

# push
      - docker-push-tag:
          tag: "master"
          requires:
            - test-integration
          filters:
            branches:
              only: master
